### ISSUE TITLE
No description of the project

### ISSUE THREAD

**Issue by nimitbhargava** [neophyt3/i2#1]
**Is the project open for contribution?** If it is so, then I can't find any contribution or project description related files.

**Comment by neophyt3** [comment]
No bud, this was interview test.. but I am planning to take it forward by adding graphql endpoint and also create tutorial for the same. 
if you are intrested in the description then its like
NodeJs, ExpressJs in es6 +( Graphql + ReactJs + CssInJs )*
_* will soon add it_

**Comment by nimitbhargava** [comment]
This sounds interesting!! @neophyt3 :)
